version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "project.clj" }}
      - run:
          command: |
            lein deps
      - save_cache:
          key: deps-{{ checksum "project.clj" }}
          paths:
            - "~/.m2"
      - run:
          command: |
            lein test

  lint:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "project.clj" }}
      - run:
          command: |
            lein deps
      - save_cache:
          key: deps-{{ checksum "project.clj" }}
          paths:
            - "~/.m2"
      - run:
          command: |
            lein cljfmt check

  deploy:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "project.clj" }}
      - run:
          name: deps
          command: |
            lein deps
      - save_cache:
          key: deps-{{ checksum "project.clj" }}
          paths:
            - "~/.m2"
      - run:
          name: run deploy
          command: |
            lein deploy clojars

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-and-test
            - lint
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*([ab][0-9]*)?/
            branches:
              ignore: /.*/




